def build(bld):
    for fil in ['keysafe.desktop', 'ksed.desktop']:
        bld(
                features='subst',
                source=fil+'.in',
                target=fil,
                dict={
                    'KEYSAFE_PY_PATH' : bld.env.KEYSAFE_PY_PATH,
                    'KEYSAFE_GLADE_PATH' : bld.env.KEYSAFE_GLADE_PATH,
                    'KEYSAFE_BIN_PATH' : bld.env.KEYSAFE_BIN_PATH,
                    },
                )

# vim: set ft=python :
