def build(bld):
    for fil in ['keysafe.desktop', 'ksed.desktop']:
        bld(
                features='subst',
                source=fil+'.in',
                target=fil,
                dict={
                    'KEYSAFE_PY_PATH' : 'pypath',
                    'KEYSAFE_GLADE_PATH' : 'gladepath',
                    'KEYSAFE_BIN_PATH' : 'binpath',
                    },
                )

# vim: set ft=python :
