def build(bld):
    for fil in ['keysafe.desktop', 'ksed.desktop']:
        bld(
                features='subst',
                source=fil+'.in',
                target=fil,
                dict={
                    'KEYSAFE_PATH' : bld.env.KEYSAFE_PATH,
                    'KEYSAFE_GLADE_PATH' : bld.env.KEYSAFE_GLADE_PATH,
                    'KEYSAFE_BIN_PATH' : bld.env.KEYSAFE_BIN_PATH,
                    },
                install_path = '${KEYSAFE_GNOME_DATA_PATH}',
                )

# how to install the schema file?
# vim: set ft=python :
