def build(bld):
    for fil in ['ksconv', 'ksdump']:
        bld(
                features='subst',
                source=fil+'.in',
                target=fil,
                chmod=0755,
                dict={
                    'KEYSAFE_PATH' : bld.env.KEYSAFE_PATH,
                    'KEYSAFE_GLADE_PATH' : bld.env.KEYSAFE_GLADE_PATH,
                    'KEYSAFE_BIN_PATH' : bld.env.KEYSAFE_BIN_PATH,
                    },
                )

# vim: set ft=python :
