def build(bld):
    for fil in ['ksconv', 'ksdump']:
        bld(features='subst',
                source=fil+'.in',
                target=fil,
                chmod=0755,
                dict={
                    'KEYSAFE_PY_PATH' : 'pypath',
                    'KEYSAFE_GLADE_PATH' : 'gladepath',
                    'KEYSAFE_BIN_PATH' : 'binpath'
                    })
