def build(bld):
    bld(
            features='cxx cshlib pyext',
            source='cryptobotan.cc  crypto.cc',
            target='cryptobotan',
            uselib='botan',
            install_path='${KEYSAFE_PY_PATH}',
            )

# todo: installation

# vim: set ft=python :
