def build(bld):
    bld(
            features='cxx cshlib pyext',
            source='cryptobotan.cc  crypto.cc',
            target='cryptobotan',
            uselib='botan',
            install_path='${KEYSAFE_PY_PATH}',
            lib='boost_python',
            )

# vim: set ft=python :
